title: Chaos Blog
description: find a way .
show_downloads: false

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://alvenchen.github.io" # change this to the base hostname & protocol for your site

github_repo: "https://github.com/alvenchen/" #

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "you only live once!"
sidebar-avatar: /images/blog.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

RSS: false
github_username:    alvenchen


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Chaos"
image: /thumbnail-jumbo.png
#twitter:
#  username: chaos
#  site:
#facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:


gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 38fe038dc8e1470fabac                            #生成的clientID
  clientSecret: 2b0ab0ba999d334b0c49fa9019397f250a97cc0b    #生成的clientSecret
  repo: blog    #仓库名称
  owner: alvenchen    #github用户名
  admin: alvenchen
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# baidu Analytics
ba_track_id: '13f15273b9491a7cbe639110ad96fbbc'

# Google Analytics
ga_track_id: 'UA-132411478-1'
ga_domain: auto
