title: Chaos Blog
description: find a way .
show_downloads: false

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://alvenchen.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Chaos"
image: /thumbnail-jumbo.png
#twitter:
#  username: chaos
#  site:
#facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:


gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 38fe038dc8e1470fabac                            #生成的clientID
  clientSecret: 2b0ab0ba999d334b0c49fa9019397f250a97cc0b    #生成的clientSecret
  repo: alvenchen.github.io    #仓库名称
  owner: alvenchen    #github用户名
  admin: alvenchen
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
